"""File storage behind a tiny interface.

Why local disk: MinIO's public image can no longer be pulled, and a Docker
volume is enough for the skeleton. To move to S3 later, write a class with the
same three methods (save_upload, path_for/open, delete) and return it from
get_storage(): the routers do not change.

Safety rules enforced here:
- keys are generated by the server (the user's filename is never used in a path)
- extension allow-list per kind + magic-byte check (a renamed .exe is rejected)
- size cap, enforced while streaming (a huge upload is cut off, not buffered)
- written to a .part file and renamed on success, so a crash never leaves a
  half-written file that looks real
"""
import hashlib
import uuid
from functools import lru_cache
from pathlib import Path

import anyio
from fastapi import HTTPException, UploadFile

from app.config import settings

CHUNK = 1024 * 1024  # 1 MB

ALLOWED = {
    "file": {".pdf", ".ppt", ".pptx", ".doc", ".docx"},
    "photo": {".jpg", ".jpeg", ".png", ".webp"},
}


def _signature_ok(ext: str, head: bytes) -> bool:
    if ext == ".pdf":
        return head.startswith(b"%PDF")
    if ext in (".pptx", ".docx"):
        return head.startswith(b"PK\x03\x04")  # zip container
    if ext in (".ppt", ".doc"):
        return head.startswith(bytes.fromhex("d0cf11e0a1b11ae1"))  # old OLE format
    if ext in (".jpg", ".jpeg"):
        return head.startswith(b"\xff\xd8\xff")
    if ext == ".png":
        return head.startswith(b"\x89PNG\r\n\x1a\n")
    if ext == ".webp":
        return head[:4] == b"RIFF" and head[8:12] == b"WEBP"
    return False


class LocalStorage:
    def __init__(self, root: str):
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def path_for(self, key: str) -> Path:
        p = (self.root / key).resolve()
        if self.root not in p.parents:  # blocks ../ tricks
            raise ValueError("invalid storage key")
        return p

    def delete(self, key: str):
        self.path_for(key).unlink(missing_ok=True)

    async def save_upload(self, upload: UploadFile, kind: str, prefix: str) -> dict:
        original = Path(upload.filename or "").name[:200]
        ext = Path(original).suffix.lower()
        if ext not in ALLOWED[kind]:
            raise HTTPException(
                422, f"For kind '{kind}', allowed types are: {', '.join(sorted(ALLOWED[kind]))}"
            )

        key = f"{prefix}/{uuid.uuid4().hex}{ext}"
        dest = self.path_for(key)
        dest.parent.mkdir(parents=True, exist_ok=True)
        tmp = dest.with_name(dest.name + ".part")

        limit = settings.max_upload_mb * 1024 * 1024
        digest = hashlib.sha256()
        size = 0
        first = True
        try:
            with open(tmp, "wb") as f:
                while chunk := await upload.read(CHUNK):
                    if first:
                        if not _signature_ok(ext, chunk[:16]):
                            raise HTTPException(422, "File content does not match its extension")
                        first = False
                    size += len(chunk)
                    if size > limit:
                        raise HTTPException(413, f"File is larger than {settings.max_upload_mb} MB")
                    digest.update(chunk)
                    # keep the event loop free while writing
                    await anyio.to_thread.run_sync(f.write, chunk)
            if size == 0:
                raise HTTPException(422, "The uploaded file is empty")
            tmp.rename(dest)
        except BaseException:
            tmp.unlink(missing_ok=True)
            raise

        return {
            "object_key": key,
            "original_filename": original,
            "content_type": upload.content_type,
            "size_bytes": size,
            "sha256": digest.hexdigest(),
        }


@lru_cache
def get_storage() -> LocalStorage:
    return LocalStorage(settings.upload_dir)